version: '3.8'
services:
  susahol-backend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - 4000:4000
    networks:
      - app-network
    volumes:
      - ./:/susahol-backend
      - ignore:/susahol-backend/node_modules

    depends_on:
      - redis

  redis:
    extends:
      file: ./services/redis/docker-compose.yml
      service: redis
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  cache:
    driver: local
  data:
    driver: local
  ignore:
