FROM node:16.13-slim

WORKDIR /

COPY ./ ./susahol-backend

WORKDIR /susahol-backend

RUN npm install --legacy-peer-deps

RUN npm install -g ts-node-dev

RUN npm install -g cross-env

RUN apt update

RUN chown -Rh node:node /susahol-backend/node_modules

EXPOSE 4000

CMD [ "cross-env", "NODE_ENV=development", "ts-node-dev","--transpile-only", "src/index.ts"]