FROM node:16.13-slim

WORKDIR /

COPY ./ ./susahol-backend

WORKDIR /susahol-backend

RUN npm install --legacy-peer-deps

RUN npm install -g ts-node-dev

RUN npm install -g cross-env

RUN apt update

RUN chown -Rh node:node /susahol-backend/node_modules

EXPOSE 4000

ENV TINI_VERSION v0.19.0

ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini

RUN chmod +x /tini

ENTRYPOINT ["/tini", "--"]

CMD [ "cross-env", "NODE_ENV=development", "ts-node-dev","--transpile-only", "src/index.ts"]